version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Run lint
          command: npm run lint:check
      - run:
          name: Run tests
          command: npm test
      - store_artifacts:
          path: test-results
      - run:
          name: Run build
          command: npm run build
  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - netlify-deploy:
          name: Netlify Deploy
          command: ./node_modules/.bin/netlify deploy --site ${NETLIFY_SITE_API_ID} --auth ${NETLIFY_ACCESS_TOKEN} --dir=dist

workflows:
  version: 2
  test-build--deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - circleci-project-setup
