version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Run lint
          command: npm run lint:check
      - run:
          name: Run tests
          command: npm test
      - store_artifacts:
          path: test-results
      - run:
          name: Run build
          command: npm run build

workflows:
  version: 2
  Build and Test:
    jobs:
      - build
