version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:14
commands:
  test_build:
    steps:
      - checkout
      - run:
          name: Set environment variables
          command: echo "${PRODUCTION_ENV}" >>  env/production.json
      - restore_cache:
          keys:
            - cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Run lint
          command: npm run lint:check
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Run build
          command: npm run build
      - run:
          name: Add support for client-side routing in Netlify
          command: echo "/*  /index.html  200" >> dist/_redirects
jobs:
  build_deploy:
    executor: node-executor
    working_directory: ~/repo
    steps:
      - test_build
      - run:
          name: Netlify Deploy
          command: ./node_modules/.bin/netlify deploy --site ${NETLIFY_SITE_API_ID} --auth ${NETLIFY_ACCESS_TOKEN} --dir=dist --prod
workflows:
  version: 2
  test-build-deploy:
    jobs:
      - build_deploy:
          filters:
            branches:
              only:
                - master
